apiVersion: v1
data:
  nginx.conf: "events {}\r\n\r\nhttp {\r\n    server {\r\n        listen 80;\r\n        server_name
    sso.postech.com.br;\r\n\r\n        location / {\r\n            proxy_pass http://keycloak:8080;\r\n
    \           proxy_set_header Host $host;\r\n            proxy_set_header X-Real-IP
    $remote_addr;\r\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\r\n
    \           proxy_set_header X-Forwarded-Proto $scheme;\r\n        }\r\n    }\r\n\r\n
    \   server {\r\n        listen 80;\r\n        server_name api.postech.com.br;\r\n\r\n
    \       location / {\r\n            proxy_pass http://host.docker.internal:8080;\r\n
    \           proxy_set_header Host $host;\r\n            proxy_set_header X-Real-IP
    $remote_addr;\r\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\r\n
    \           proxy_set_header X-Forwarded-Proto $scheme;\r\n        }\r\n    }\r\n}\r\n"
kind: ConfigMap
metadata:
  name: nginx-config
