apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

        server {
            listen 80;
            server_name sso.postech.com.br;

            location / {
                set $upstream_keycloak keycloak.default.svc.cluster.local;
                proxy_pass http://$upstream_keycloak:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;
            server_name api.postech.com.br;

            location / {
                set $upstream_app app.default.svc.cluster.local;
                proxy_pass http://$upstream_app:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80 default_server;
            server_name _;

            location / {
                set $upstream_default app.default.svc.cluster.local;
                proxy_pass http://$upstream_default:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
