name: Upload Reports
description: Upload Reports from Jacoco and Test Results to GitHub Actions Artifacts

runs:
  using: composite
  steps:
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/reports/jacoco/test/
        if-no-files-found: error

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/test/
        if-no-files-found: warn