spring.application.name=oficina-mecanica

spring.datasource.url=jdbc:postgresql://localhost:5432/oficina
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.config.import=optional:file:.env[.properties]

# Keycloak OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

# Springdoc / Swagger UI
springdoc.swagger-ui.oauth.client-id=${KEYCLOAK_CLIENT_ID:oficina}
springdoc.swagger-ui.oauth.client-secret=
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha