spring.application.name=oficina-mecanica

spring.datasource.url=jdbc:postgresql://localhost:5432/oficina
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.operationsSorter=(a,b)=>{const order={post:1,put:2,patch:3,delete:4,get:5};return (order[a.get("method")]||99)-(order[b.get("method")]||99);}
