apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/part-of: oficina
data:
  POSTGRES_DB: "oficina"
  KEYCLOAK_DB: "keycloak"
  KEYCLOAK_REALM: "Fiap"
  KEYCLOAK_CLIENT_ID: "oficina"
