apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
data:
  SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonarqube"
  SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
  SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dnode.store.allow_mmap=false"