apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: sonarqube-data }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: sonarqube-extensions }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 500Mi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: sonarqube-logs }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 500Mi } }