-- ============================================================
-- Migração inicial - esquema da Oficina Mecânica
-- Gerado a partir das entidades JPA em
-- br.com.fiap.oficina.infrastructure.persistence.entity
-- Banco de dados: PostgreSQL
-- ============================================================

-- ------------------------------------------------------------
-- Endereços (EnderecoJpaEntity)
-- ------------------------------------------------------------
CREATE TABLE enderecos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro  VARCHAR(100) NOT NULL,
    numero      VARCHAR(25) NOT NULL,
    complemento VARCHAR(50),
    bairro      VARCHAR(50) NOT NULL,
    cidade      VARCHAR(50) NOT NULL,
    estado      VARCHAR(2) NOT NULL,
    cep         VARCHAR(10) NOT NULL
);

-- ------------------------------------------------------------
-- Clientes (ClienteJpaEntity + DocumentoEmbeddable)
-- ------------------------------------------------------------
CREATE TABLE clientes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(100) NOT NULL,
    documento_numero VARCHAR(20) NOT NULL,
    tipo_pessoa      VARCHAR(25) NOT NULL,
    email            VARCHAR(50) NOT NULL,
    endereco_id      BIGINT,
    CONSTRAINT uk_clientes_documento_numero UNIQUE (documento_numero),
    CONSTRAINT uk_clientes_email UNIQUE (email),
    CONSTRAINT fk_clientes_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos (id)
);

-- ------------------------------------------------------------
-- Contatos (ContatoJpaEntity)
-- ------------------------------------------------------------
CREATE TABLE contatos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo       VARCHAR(50) NOT NULL,
    nome       VARCHAR(50) NOT NULL,
    telefone   VARCHAR(20) NOT NULL,
    cliente_id BIGINT,
    CONSTRAINT fk_contatos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

-- ------------------------------------------------------------
-- Veículos (VeiculoJpaEntity)
-- ------------------------------------------------------------
CREATE TABLE veiculos (
    id_veiculo   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca        VARCHAR(50) NOT NULL,
    nome         VARCHAR(50) NOT NULL,
    modelo       VARCHAR(50) NOT NULL,
    ano          VARCHAR(10) NOT NULL,
    placa        VARCHAR(7)   NOT NULL,
    motorista_id BIGINT       NOT NULL,
    CONSTRAINT uk_veiculos_placa UNIQUE (placa),
    CONSTRAINT fk_veiculos_motorista FOREIGN KEY (motorista_id) REFERENCES clientes (id)
);

-- ------------------------------------------------------------
-- Peças (PecaJpaEntity)
-- ------------------------------------------------------------
CREATE TABLE pecas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20)   NOT NULL,
    nome            VARCHAR(100)   NOT NULL,
    descricao       VARCHAR(200),
    fabricante      VARCHAR(100),
    fornecedor      VARCHAR(100),
    preco_de_compra NUMERIC(10, 2),
    preco_de_venda  NUMERIC(10, 2) NOT NULL,
    qtd_estoque     INTEGER        NOT NULL,
    ativo           BOOLEAN        NOT NULL,
    CONSTRAINT uk_pecas_codigo UNIQUE (codigo)
);

-- ------------------------------------------------------------
-- Funcionários (FuncionarioEntity) — criado antes de servicos
-- pois servicos referencia funcionarios via FK.
-- ------------------------------------------------------------
CREATE TABLE funcionarios (
    id             UUID PRIMARY KEY,
    nome           VARCHAR(100) NOT NULL,
    cargo          VARCHAR(50) NOT NULL
);

-- ------------------------------------------------------------
-- Serviços (ServicoJpaEntity)
-- ------------------------------------------------------------
CREATE TABLE servicos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao      VARCHAR(100) NOT NULL,
    status         VARCHAR(50) NOT NULL,
    funcionario_id UUID       NOT NULL,
    cliente_id     BIGINT       NOT NULL,
    veiculo_id     BIGINT       NOT NULL,
    CONSTRAINT fk_servicos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_servicos_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos (id_veiculo),
    CONSTRAINT fk_servicos_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios (id)
);

-- ------------------------------------------------------------
-- Peças utilizadas em cada serviço (ElementCollection de Servico)
-- ------------------------------------------------------------
CREATE TABLE servico_pecas (
    servico_id BIGINT NOT NULL,
    peca_id    BIGINT NOT NULL,
    CONSTRAINT fk_servico_pecas_servico FOREIGN KEY (servico_id) REFERENCES servicos (id),
    CONSTRAINT fk_servico_pecas_peca FOREIGN KEY (peca_id) REFERENCES pecas (id)
);

